#! /usr/bin/env ruby

require 'rock/bundle'
require 'orocos'
require './monitor_gps.rb'
include Orocos

Bundles.initialize

Orocos::Process.run 'gps::MB500Task' => 'Task', :output => 'dgps-log.txt' do |p|
    task = p.task('Task')

    task.apply_conf(['default'])

    task.configure
    task.start

    Orocos.log_all_ports

    monitor_gps(task)
end

